### ISSUE TITLE
High level cities can't be visited by low-level character

### ISSUE THREAD

**Issue by archer-voodoo** [epsilion-war-mmorpg/epsilion_wars_mmorpg_automation#28]
Когда персонаж стремится к ремонту и пересекает локацию "Цирта", он затем пытается пройти через "Миледон", доступный лишь с 30 уровня.

Из-за этого персонаж застревает в режиме фарма.

Линия кода, которая выбирает путь в Миледон и не учитывает ограничения по уровню:
https://github.com/epsilion-war-mmorpg/epsilion_wars_mmorpg_automation/blob/master/epsilion_wars_mmorpg_automation/trainer/handlers/farming.py#L102

**Comment by shatokh** [comment]
@archer-voodoo 
привет. Не воспроизводил. А зачем пересекать локацию Цирта для ремонта,если в Цирте есть ремонтер?
Классический пример. Персонаж фармит в Тракте. Хотим рематься в Цирте. Запускаем с аргументом 
--path "грей,цир" . Ни в какой Миледон соотвественно и не ломится.

**Comment by esemi** [comment]
Проблема с попыткой пойти в Миледон проявляется, когда неверно сконфигурирован путь до ремонтника - тогда персонаж пытается идти в первй из город в списке кнопок, а там как раз Миледон (когда персонаж в Цирте)

**Comment by archer-voodoo** [comment]
Как вы думаете если добавить проверку уровня персонажа и устанавливать --path "грей,цир" по умолчанию для персонажей меньше 30 уровня в случае когда не другая конфигурация

**Comment by esemi** [comment]
Есть решение понадёжнее - держать в игре весь список путей до ближайшего ремонтика)
Я пока это тестирую в приватной версии бота)
