### ISSUE TITLE
Instant merchant can stop farming when met with instant lottery

### ISSUE THREAD

**Issue by archer-voodoo** [epsilion-war-mmorpg/epsilion_wars_mmorpg_automation#29]
Когда герой наталкивается на торговца, предлагающего моментальную лотерею, он останавливается перед ним. Это напоминает ситуацию, когда в тексте упоминается "Свиток Кселеса", и персонаж начинает думать, что нашел именно его.

**Comment by esemi** [comment]
Удалил совсем список стоп-слов для торговца. По-умолчанию бот его пропускает. Если нужно останавливаться - `echo skip_random_vendor=false >> .env`

**Comment by archer-voodoo** [comment]
Предлагаю оставить список стоп-слов тоже это очень полезно. Просто по умолчанию пропускать торговца
