### ISSUE TITLE
Character don't use movement bind after dying in PVP

### ISSUE THREAD

**Issue by archer-voodoo** [epsilion-war-mmorpg/epsilion_wars_mmorpg_automation#30]
Если персонаж умирает в ПВП и у него вещь ломается, он не использует бинд для передвижения

**Comment by shatokh** [comment]
@archer-voodoo привет. Так же не воспроизводил. При поломке в пвп или в пве, разницы нет. Юзает билд 1 чтобы ходить и 2,как дошел в фарм локацию. Единственный баг как по мне,то что в документации указано обратное. Можно пофиксить вводом сеттингов equip_farming_number и equip_travel_number
@esemi посмотри пжст почему дефолт сбился на обратный
equip_farming_number: Binding number of your farming equipment set. By default 1.
equip_travel_number: Binding number of your travel gear. By default 2.

**Comment by shatokh** [comment]
![image](https://github.com/user-attachments/assets/92bcbf2f-241c-46c1-b189-72bfcad5646a)
settings looks ok

**Comment by esemi** [comment]
> Если персонаж умирает в ПВП и у него вещь ломается, он не использует бинд для передвижения
Да, в некоторых случаях использование бинда игнорируется. Так сделано ради упрощения поддержки кода - очень много разных вариантов "что может случиться" и тяжело поддерживать матрицу принятия решений для выбора бинда (или не использования его совсем).
Возможно в будущем перенесу сюда новую версию кода, там нужный бинд используется всегда перед целевым действием, как то "поиск врага" и "открыли карту чтобы двигаться"

Но пока тикет закрою, не вижу что тут можно быстро пофиксить
